theme: jekyll-theme-architect

title: Zoe's personal website
url: https://emma-sax4.github.io/zoesax301.github.io
markdown: kramdown

github:
  repo_url: https://github.com/zoesax301/zoesax301.github.io
  repo: zoesax301.github.io
  owner_url: https://github.com/zoesax301
  owner: zoesax301

kramdown:
  smart_quotes: ["rdquo", "rsquo", "quot", "quot"]

sass:
  style: compressed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock

relative_links:
  enabled: true
  collections: true
